### ISSUE TITLE
Accès à "mon compte"

### ISSUE THREAD

**Issue by andasilva** [HE-Arc/LesBonsDeals#7]
Une fois connecté, il n'y a pas le bouton pour accéder à "mon compte" depuis la barre de navigation (c'est-à-dire /home).

**Comment by AxelRieben** [comment]
Il y est chez moi, par contre le menu contextuel dépasse à moitié du navigateur (en mode plein écran).

**Comment by andasilva** [comment]
Merci pour le feedback, merci de le positionner correctement 😄
